name: release

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php_version: "8.1"
            php_number: "81"
            tag_suffix: "8.1"

          - php_version: "8.2"
            php_number: "82"
            tag_suffix: "8.2"

          - php_version: "8.3"
            php_number: "83"
            tag_suffix: "8.3"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          # Build and push the image
          docker buildx build --push \
            --platform=linux/amd64 \
            --build-arg="PHP_VERSION=${{ matrix.php_version }}" \
            --build-arg="PHP_NUMBER=${{ matrix.php_number }}" \
            --tag adityadarma/alpine-phpbolt:${{ matrix.tag_suffix }} .